### PR TITLE
Introduce AutoFixture

### PR DESCRIPTION
**Pull request by mitikov**

### CODE REVIEW

**Comment by vadimzozulya** [comment]
The tests are samples. The simpler samples are the better. AutoFixture is a great tool, but from my point of view, not in this case :)

**Comment by mitikov** [comment]
Tests could be used as both as a reference, and safety harness during development.

Using fixed data in tests may give a false sense of safety, when all tests green, but code randomly fails.

In this case, we keep both fixed (easy to debug) and random data.

The future intent is to follow TTD during development and not deal with complicated data arrangements.

**Comment by smarchenko** [comment]
I am not a big fan of using AutoFixture for such simple tests like these ones. 
However, I must admit that I agree with your argument related to the fixed test data. 
What I do not like for sure is using AutoFixture for only part of tests :)

To have this change merged we need to be consistent and rework other tests to use AutoFixture. Sorry.

**Comment by vadimzozulya** [comment]
> Using fixed data in tests may give a false sense of safety, when all tests green, but code randomly fails.

Author of the code should cover all cases, and it's not a question of tools :) 
What if you have chance to fail 1 to 1000000? You need 1000000 test run to catch a problem, but if tests are executed once in a year... well not sure that statement is completely valid :)

**Pull request merged**
